services:
  waku-musicbot:
    container_name: waku-musicbot
    build: .
    image: waku-musicbot:local
    network_mode: host
    restart: always
    volumes:
      - ./config.js:/usr/src/app/config.js:ro
      - ./data:/usr/src/app/data
