services:
  discordmusicbot:
    container_name: discordmusicbot
    build: .
    image: discordmusicbot:local
    network_mode: host
    restart: always
    volumes:
      - ./config.js:/usr/src/app/config.js:ro
      - ./commands:/usr/src/app/commands
      - ./lib:/usr/src/app/lib
      - ./events:/usr/src/app/events
      - ./util:/usr/src/app/util
      - ./api:/usr/src/app/api
      - ./index.js:/usr/src/app/index.js
      - ./data:/usr/src/app/data